version: '3.1'
services: 
  app: 
    container_name: app
    environment:
      ENV_FOR_DYNACONF: docker
    links:
      - mysql
    image: giuliaioana/python_flask_app:0.14
    ports: 
      - 5000:5000
    volumes: 
      - ./src/main.py:/main.py:rw
    #  - ./src/settings.yaml:/settings.yaml:rw
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - "3306:3306"
    # volumes:
    #   - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    #   - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
  