version: '3.1'
services: 
  app: 
    # networks:
    #   - ubuntu_default
    environment:
      ENV_FOR_DYNACONF: docker
    # placement:
    #   constraints: [node.labels.worker == true]
    #   preferences:
    #     - spread: node.labels.worker
    image: giuliaioana/python_flask_app:latest
    ports: 
      - 5000:5000
    # volumes: 
    #   - ./src/main.py:/main.py:rw
      #- ./src/settings.yaml:/settings.yaml:rw
