version: '3.1'
services: 
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    deploy:
      placement:
        constraints: [node.labels.FE == true]

# networks:
#   ubuntu_default:
#     external: true
