version: '3.1'
services: 

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    # placement:
    #   constraints: [node.labels.worker == true]
    #   preferences:
    #     - spread: node.labels.worker
