version: '3.1'
services: 
  
  worker:
    #build: worker
    image: giuliaioana/worker:latest
    # volumes:
    #   - ./src/worker:/app
    environment:
      ENV_FOR_DYNACONF: docker
      SWARM: True
    # placement:
    #   constraints: [node.labels.worker == true]
    #   preferences:
    #     - spread: node.labels.worker
