version: '3.8'
services: 
  
  worker:
    image: giuliaioana/worker:1.1.99
    environment:
      ENV_FOR_DYNACONF: docker
      SWARM: "True"
    deploy:
      placement:
        constraints: [node.labels.FE == true]
    secrets:
      - DB_PASSWORD
secrets:
  DB_PASSWORD:
    external: true
