version: '3.1'
services: 
  
  worker:
    name: worker
    image: giuliaioana/worker:latest
    volumes:
      - /home/ubuntu/PythonFlask/src/worker:/app
    environment:
      ENV_FOR_DYNACONF: docker
      SWARM: "True"
    deploy:
      placement:
        constraints: [node.labels.FE == true]
        preferences:
          - spread: node.labels.FE
