FROM jenkins/inbound-agent
USER root

RUN apt-get update\
        && apt-get install -y python3 \
        && apt-get install -y python3-pip \
        && pip install --upgrade pip \
        && pip install flake8
USER jenkins
